# Generated by Django 3.0.7 on 2020-07-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='المكان')),
                ('price', models.IntegerField(verbose_name='السعر')),
                ('date', models.DateField(verbose_name='معاد الرحله')),
                ('time', models.TimeField(verbose_name='معاد الصعود')),
                ('days_lenght', models.IntegerField(verbose_name='مده الرحله ')),
            ],
        ),
    ]
