# Generated by Django 3.0.7 on 2020-06-28 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALL_COURSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=50)),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.cate')),
            ],
        ),
        migrations.DeleteModel(
            name='course',
        ),
    ]
