# Generated by Django 3.0.7 on 2020-06-24 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import job.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='job_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vacancy', models.IntegerField(default=1)),
                ('company_name', models.CharField(max_length=50, null=True, verbose_name='اسم الشركه :')),
                ('job_name', models.CharField(max_length=254, null=True, verbose_name='اسم الوظيفه')),
                ('address_country', models.CharField(max_length=50, null=True, verbose_name='الدوله ')),
                ('address_city', models.CharField(max_length=50, null=True, verbose_name='المدينه')),
                ('address_area', models.CharField(max_length=50, null=True, verbose_name='المنطقه')),
                ('About_the_Job', models.TextField(null=True, verbose_name='تفاصيل الوظيفه')),
                ('description', models.TextField(max_length=1000)),
                ('Job_Requirements', models.TextField(null=True, verbose_name='متطلبات الوظيفه')),
                ('Career_Level', models.CharField(choices=[('student', 'student'), ('Entry Level', 'Entry Level'), ('Experienced', 'Experienced'), ('manager', 'manager'), ('Senior Management', 'Senior Management')], max_length=30, null=True, verbose_name='مستوى الخبره')),
                ('Email', models.EmailField(max_length=254, null=True, verbose_name='البريد الالكترونى للشركه')),
                ('JOB_type', models.CharField(choices=[('Full time', 'Full time'), ('Freelancer', 'Freelancer'), ('Part-time', 'Part time'), ('Internship', 'Internship ')], default='FULL TIME', max_length=30, null=True, verbose_name='نوع الشغل')),
                ('available', models.BooleanField(null=True, verbose_name='متاح')),
                ('Company_details', models.TextField(null=True, verbose_name='معلومات عن الشركه ')),
                ('Created', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' وقت نشر الوظيفه')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='وقت تعديل الوظيفه')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('salary', models.IntegerField(default=0, verbose_name='المرتب')),
                ('experience', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to=job.models.image_upload, verbose_name='صوره')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('webiste', models.URLField()),
                ('cv', models.FileField(upload_to='apply/')),
                ('cover_letter', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='job.job_data')),
            ],
        ),
    ]
