# Generated by Django 3.0.7 on 2020-06-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200624_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='About_the_Job',
        ),
    ]
